# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\"\x1a\n\x04\x42\x61se\x12\x12\n\nbaseNumber\x18\x01 \x01(\x03\"&\n\rNumberSquared\x12\x15\n\rnumberSquared\x18\x01 \x01(\x03\x32\x38\n\rSquareService\x12\'\n\x0cSquareNumber\x12\x05.Base\x1a\x0e.NumberSquared\"\x00\x62\x06proto3')
)




_BASE = _descriptor.Descriptor(
  name='Base',
  full_name='Base',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseNumber', full_name='Base.baseNumber', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=43,
)


_NUMBERSQUARED = _descriptor.Descriptor(
  name='NumberSquared',
  full_name='NumberSquared',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numberSquared', full_name='NumberSquared.numberSquared', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['Base'] = _BASE
DESCRIPTOR.message_types_by_name['NumberSquared'] = _NUMBERSQUARED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Base = _reflection.GeneratedProtocolMessageType('Base', (_message.Message,), dict(
  DESCRIPTOR = _BASE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:Base)
  ))
_sym_db.RegisterMessage(Base)

NumberSquared = _reflection.GeneratedProtocolMessageType('NumberSquared', (_message.Message,), dict(
  DESCRIPTOR = _NUMBERSQUARED,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:NumberSquared)
  ))
_sym_db.RegisterMessage(NumberSquared)



_SQUARESERVICE = _descriptor.ServiceDescriptor(
  name='SquareService',
  full_name='SquareService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=85,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='SquareNumber',
    full_name='SquareService.SquareNumber',
    index=0,
    containing_service=None,
    input_type=_BASE,
    output_type=_NUMBERSQUARED,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SQUARESERVICE)

DESCRIPTOR.services_by_name['SquareService'] = _SQUARESERVICE

# @@protoc_insertion_point(module_scope)
