# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import service_pb2 as service__pb2


class SquareServiceStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SquareNumber = channel.unary_unary(
        '/SquareService/SquareNumber',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=service__pb2.NumberSquared.FromString,
        )


class SquareServiceServicer(object):
  """The greeting service definition.
  """

  def SquareNumber(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SquareServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SquareNumber': grpc.unary_unary_rpc_method_handler(
          servicer.SquareNumber,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=service__pb2.NumberSquared.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SquareService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
